POST http://127.0.0.1:8000/generate
Content-Type: application/json

{
    "width": 1000,
    "height": 1000,
    "format": "jpg",
    "quality": 10,
    "path": "kek.pdf",
    "watermark": {
        "rotate": -45,
        "position": "center",
        "opacity": 0.1
    }
}